"""
Shopper Spectrum — Streamlit app (multipage).

Run from the project root:
    streamlit run app/app.py

The Product Recommendation, Customer Segmentation and Analytics Dashboard
modules live under app/pages/ and appear in the sidebar automatically.
"""

import streamlit as st

from utils import load_artifacts

st.set_page_config(page_title="Shopper Spectrum", page_icon="🛒", layout="wide")

st.title("🛒 Shopper Spectrum")
st.caption("Customer Segmentation & Product Recommendations in E-Commerce")

# Fail gracefully if the pipeline hasn't been run yet.
try:
    load_artifacts()
    ok = True
except Exception as e:
    ok = False
    err = str(e)

if not ok:
    st.error(
        "Model artifacts not found. Run the training pipeline first:\n\n"
        "```bash\npython -m shopper_spectrum.cli train\n```\n\n"
        f"Details: {err}"
    )
    st.stop()

st.success("Models loaded. Use the sidebar to navigate between modules. 👈")

st.markdown(
    """
### What's inside

- **🎯 Product Recommendation** — enter a product name, get 5 similar products
  (item-based collaborative filtering with cosine similarity).
- **🔍 Customer Segmentation** — enter a customer's Recency, Frequency and
  Monetary values to predict their segment.
- **📊 Analytics Dashboard** — explore the EDA visuals, segment profiles and
  the product similarity heatmap generated by the pipeline.

---

**Customer segments**

| Segment | Meaning |
|---|---|
| 🟢 **High-Value** | Recent, frequent, big spenders — reward & retain |
| 🔵 **Regular** | Steady purchasers — nurture toward high-value |
| 🟡 **Occasional** | Rare, low-spend — re-engage |
| 🔴 **At-Risk** | Haven't purchased in a long time — win back |
"""
)
