"""Analytics Dashboard — surfaces the figures and reports from the pipeline."""

from pathlib import Path

import pandas as pd
import streamlit as st

from utils import FIG_DIR, REPORTS_DIR

st.set_page_config(page_title="Analytics Dashboard", page_icon="📊", layout="wide")

st.title("📊 Analytics Dashboard")
st.write("EDA, clustering and recommender insights generated by the training pipeline.")


def show(name: str, caption: str):
    p = Path(FIG_DIR) / name
    if p.exists():
        st.image(str(p), caption=caption, use_container_width=True)
    else:
        st.info(f"`{name}` not found — run the pipeline to generate it.")


# Segment profiles table
profiles_path = Path(REPORTS_DIR) / "segment_profiles.csv"
if profiles_path.exists():
    st.subheader("Segment profiles")
    st.dataframe(pd.read_csv(profiles_path), use_container_width=True)

tab1, tab2, tab3 = st.tabs(["Exploratory Analysis", "Clustering", "Recommender"])

with tab1:
    c1, c2 = st.columns(2)
    with c1:
        show("top_countries.png", "Transaction volume by country")
        show("revenue_trend.png", "Monthly revenue over time")
        show("transaction_value_dist.png", "Monetary per transaction")
    with c2:
        show("top_products.png", "Top-selling products")
        show("rfm_distributions.png", "RFM distributions")
        show("customer_value_dist.png", "Monetary per customer")

with tab2:
    c1, c2 = st.columns(2)
    with c1:
        show("elbow_silhouette.png", "Elbow & silhouette (KMeans)")
        show("cluster_scatter.png", "Segments: Recency vs Monetary")
    with c2:
        show("algorithm_comparison.png", "KMeans vs Hierarchical vs GMM")
        show("cluster_scatter_3d.png", "3D RFM segments")

with tab3:
    show("similarity_heatmap.png", "Product similarity heatmap (top 20 products)")
